<script src="<?php echo $this->jqPlotMin; ?>"></script>
<script src="<?php echo $this->jqPlotPieRender; ?>"></script>

<div id="chart1"></div>
<div id="chart2"></div>
<div id="chart3"></div>
<div id="chart4"></div>
<div id="chart5"></div>
<div id="chart6"></div>
<div id="chart7"></div>
<div id="chart8"></div>
<div id="chart9"></div>
<div id="chart10"></div>

<script>
      <?php foreach( $this->seArray as $nr => $se ) :?>  
      var data = <?php $str = "["; foreach ($se as $engine) {
              $title = htmlentities(utf8_decode($engine["title"]));
                    $str.= "['".$engine["label"]."', ".$engine["visits"]."],";
                }
            echo substr($str, 0, -1)."]";
            ?>;
      var plot1 = jQuery.jqplot ('chart<?php echo $nr; ?>', [data],
        {
          title: '<?php echo $title ?>', 
          seriesDefaults: {
            // Make this a pie chart.
            renderer: jQuery.jqplot.PieRenderer,
            rendererOptions: {
              // Put data labels on the pie slices.
              // By default, labels show the percentage of the slice.
              showDataLabels: true,
              seriesColors: [ "#788eff", "#fffa78", "#b8f5fb", "#aeff78", "#cb78ff", "#ff7878", "#ffbb78", "#d4ff78", "#78ffa4", "#ab78ff" ]
            }
          }
        }
      );
      <?php endforeach; ?>
</script>