<style>
    .clearfix:after {
        content: ".";
        display: block;
        height: 0;
        clear: both;
        visibility: hidden;
    }

    .piwik_container_graph_100pt_column{
        border: 1px solid #000;
        border-radius: 5px;
        background-color: #fff;
        padding: 5px;
        width: 1030px;
        float: left;
        margin: 10px 0 0 10px;
    }

    .piwik_container_graph_50pt_column{
        border: 1px solid #000;
        border-radius: 5px;
        background-color: #fff;
        padding: 5px;
        width: 500px;
        float: left;
        margin: 15px 10px 5px 10px;
        min-height: 215px;
    }

    .piwik_container_graph_50pt_column table{margin: 10px 0;}

    .piwik_container_graph_50pt_column table td.value{
        text-align: center;
        font-weight: bold;
        padding-right: 25px;
        padding-bottom: 5px;
    }

    .piwik_container_graph_50pt_column table td.pad_r{padding-right: 20px;}

    .piwik_container_graph_50pt_column table td.value_name{font-style: italic;}

    .piwik_container_graph_50pt_column table thead th{
        font-weight: normal;
        padding-right: 30px;
    }

    .piwik_container_graph_50pt_column h2 span{
        font-weight: normal;
        font-size: 10px;
    }

    .piwik_container_graph_50pt_column ol{
        margin-top: 10px;
        padding: 0;
    }
    
    .piwik_container_graph_50pt_column ol li{
        font-size: 13px;
        margin-bottom: 5px;
    }
    
    .piwik_container_graph_50pt_column ol li span{
        font-size: 10px;
        font-style: italic;
    }
    
    .piwik_container_graph_50pt_column ol li span img{
        margin: 5px 2px 0 0;
    }
    
    #cformHeader h2 span{
        font-size: 13px;
        font-weight: bold;
    }

    #page_select{
        float: left;
        margin-left: 10px;
    }

    #container_formelements{
        border: 1px solid #000;
        background-color: #dfdfdf;
    }

    #container_formelements h2{
        float: left;
        font-size: 12px;
        font-weight: normal;
    }

    .container{padding: 3px;margin: 5px 0;}

    #submit_btn{padding: 3px;}

    .container ul{
        list-style: none;
        font-size: 12px;
        font-weight: normal;
        float: left;
        padding: 0;
        margin: 0;
    }

    .container ul li{float: left;}

    .container{border-bottom: 1px solid #ccc;}

    .noborder{border: none;}

    #greyOverlay{
        display:none;
        position:absolute;
        top:0px;
        left:0px;
        bottom:0px;
        right:0px;
        width:100%;
        height:200%;
        z-index: 1;
        background-color: #222;
        opacity: 0.7;
        filter: Alpha(Opacity=70);
    }

    #greyOverlay #loading_ie{
        display: none;
        color: #fff;
        font-size: 20px;
    }
    
    #container_extend_min_height{height: 462px;}
    #container_extend_min_height[id]{height: auto;min-height: 462px;} 
    
    #show_se_info_1,#show_se_info_2,#show_se_info_3,#show_se_info_4,
    #show_se_info_5,#show_se_info_6,#show_se_info_7,#show_se_info_8,
    #show_se_info_9,#show_se_info_10{cursor: pointer;}
    
    #se_container_1,#se_container_2,#se_container_3,#se_container_4,
    #se_container_5,#se_container_6,#se_container_7,#se_container_8,
    #se_container_9,#se_container_10{display: none;}
    
    #close_all_infos{
        cursor: pointer;
        margin-left: 300px;
    }
    
    #piwik_container{width: 1100px;}
    
    #demo_info{
        background-color: #dfdfdf;
        border: 1px solid #333;
        margin: 0 10px 0 12px ;
        padding: 5px;
    }
    
    #demo_info h1{
        font-size: 20px;
        font-style: italic;
        margin-bottom: 15px;
    }
    
    #demo_info p{margin-bottom: 10px;}
    
    #demo_info #info{
        border: 1px solid red;
        padding: 10px 0 10px 300px;
        font-size: 16px;
        background-color: darkred;
        color: #fff;
    }
</style>
<!--[if IE]>
    <style>
         #page_select,.container ul,.container ul li,#container_formelements h2{float: none!important;display:inline!important;}
         .piwik_container_graph_100pt_column{width:1010px!important;}
    </style>
 <![endif]-->
<script type="text/javascript" src="<?php echo $this->SRCspin ?>"></script>
<script type="text/javascript" src="<?php echo $this->SRCspinmin ?>"></script>
<script>
    $(document).ready(function(){
        $('form').submit(function(){
            $('#greyOverlay').show();
            var opts = {
                lines: 13, // The number of lines to draw
                length: 16, // The length of each line
                width: 14, // The line thickness
                radius: 25, // The radius of the inner circle
                corners: 1, // Corner roundness (0..1)
                rotate: 0, // The rotation offset
                color: '#ddd', // #rgb or #rrggbb
                speed: 1, // Rounds per second
                trail: 44, // Afterglow percentage
                shadow: true, // Whether to render a shadow
                hwaccel: false, // Whether to use hardware acceleration
                className: 'spinner', // The CSS class to assign to the spinner
                zIndex: 2e9, // The z-index (defaults to 2000000000)
                top: '350', // Top position relative to parent in px
                left: 'auto' // Left position relative to parent in px
            };
            var target = document.getElementById('greyOverlay');
            var spinner = new Spinner(opts).spin(target);
        })
        
        $('#show_se_info_1').click(function(){
            $('#se_container_1').show();
            $('#se_container_1,#se_container_2,#se_container_3,#se_container_4,#se_container_5,#se_container_6,#se_container_7,#se_container_8,#se_container_9,#se_container_10').hide();
        });
        $('#show_se_info_1').click(function(){
            $('#se_container_1').show();
            $('#se_container_2,#se_container_3,#se_container_4,#se_container_5,#se_container_6,#se_container_7,#se_container_8,#se_container_9,#se_container_10').hide();
        });
        $('#show_se_info_2').click(function(){
            $('#se_container_2').show();
            $('#se_container_1,#se_container_3,#se_container_4,#se_container_5,#se_container_6,#se_container_7,#se_container_8,#se_container_9,#se_container_10').hide();
        });
        $('#show_se_info_3').click(function(){
            $('#se_container_3').show();
            $('#se_container_1,#se_container_2,#se_container_4,#se_container_5,#se_container_6,#se_container_7,#se_container_8,#se_container_9,#se_container_10').hide();
        });
        $('#show_se_info_4').click(function(){
            $('#se_container_4').show();
            $('#se_container_1,#se_container_2,#se_container_3,#se_container_5,#se_container_6,#se_container_7,#se_container_8,#se_container_9,#se_container_10').hide();
        });
        $('#show_se_info_5').click(function(){
            $('#se_container_5').show();
            $('#se_container_1,#se_container_2,#se_container_3,#se_container_4,#se_container_6,#se_container_7,#se_container_8,#se_container_9,#se_container_10').hide();
        });
        $('#show_se_info_6').click(function(){
            $('#se_container_6').show();
            $('#se_container_1,#se_container_2,#se_container_3,#se_container_4,#se_container_5,#se_container_7,#se_container_8,#se_container_9,#se_container_10').hide();
        });
        $('#show_se_info_7').click(function(){
            $('#se_container_7').show();
            $('#se_container_1,#se_container_2,#se_container_3,#se_container_4,#se_container_5,#se_container_6,#se_container_8,#se_container_9,#se_container_10').hide();
        });
        $('#show_se_info_8').click(function(){
            $('#se_container_8').show();
            $('#se_container_1,#se_container_2,#se_container_3,#se_container_4,#se_container_5,#se_container_6,#se_container_7,#se_container_9,#se_container_10').hide();
        });
        $('#show_se_info_9').click(function(){
            $('#se_container_9').show();
            $('#se_container_1,#se_container_2,#se_container_3,#se_container_4,#se_container_5,#se_container_6,#se_container_7,#se_container_8,#se_container_10').hide();
        });
        $('#show_se_info_10').click(function(){
            $('#se_container_10').show();
            $('#se_container_1,#se_container_2,#se_container_3,#se_container_4,#se_container_5,#se_container_6,#se_container_7,#se_container_8,#se_container_9').hide();
        });
        $('#close_all_infos').click(function(){
            $('#se_container_1,#se_container_2,#se_container_3,#se_container_4,#se_container_5,#se_container_6,#se_container_7,#se_container_8,#se_container_9,#se_container_10').hide();
        });
    });
</script>
<div id="greyOverlay">&nbsp;</div>

<div id="lwAdminMainInputWrapperNoTabs">
    <div id="cformHeader" class="clearfix">
        <form action="<?php echo $this->adress ?>" method="POST" >

            <div id="container_formelements" class="clearfix">
                <div class="container clearfix">
                    <h2>Aktuelle angezeige f&uuml;r : [ <span><?php echo $this->pagename ?></span> ]</h2>
                </div>

                <?php if($this->no_default_portal): ?>
                <div class="container clearfix">
                    <h2>Portal :</h2>
                    <select id="page_select" name="selected_page" size="1">
                        <?php foreach($this->allPortals as $page): ?>
                            <option value="<?php echo $page["idsite"]; ?>" <?php if($this->pageId == $page["idsite"]): ?>selected<?php endif; ?>><?php echo $page["name"]; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <?php endif; ?>
                
                <div class="container clearfix">
                    <h2>Zeitraum :</h2>
                    <ul>
                        <li><input type="radio" name="time_filter" value="last_week" <?php if($this->timeFilter == "last_week"): ?>checked="checked"<?php endif; ?> >&nbsp;Woche</li>
                        <li><input type="radio" name="time_filter" value="last_month" <?php if($this->timeFilter == "last_month"): ?>checked="checked"<?php endif; ?> >&nbsp;Monat</li>
                        <li><input type="radio" name="time_filter" value="last_year" <?php if($this->timeFilter == "last_year"): ?>checked="checked"<?php endif; ?> >&nbsp;Jahr</li>
                    </ul>
                </div>

                <div class="container clearfix noborder">
                    <input type="hidden" name="sent" value="1"/> 
                    <input type="submit" value="Seitenstatistik anzeigen" id="submit_btn"/>   
                </div>

            </div>
        </form>

    </div>        
    <?php if($this->demo_info): ?>
    <div id="demo_info">
        <h1>Aktuell werden Demodaten von Piwik angezeigt !</h1>
        <p> Es muss die Contentory Config angepasst werden. Die Config muss um folgenden Eintrag erweitert werden.</p>
        <p id="info">
            [piwik]<br>
            token_auth = "anonymous"<br>
            base = "http://demo.piwik.org/index.php?module=API"<br>
            default_portal = ""<br>
        </p>
        <p>
            - Ersetzen Sie "anonymous" mit dem token_auth Ihrer Piwik-Installation<br>
            - Ersetzen Sie "http://demo.piwik.org/index.php" mit dem Pfad zu Ihrer Piwik-Installation<br>
            - Tragen Sie bei default_portal den Namen ein, welchen Sie bei der Erstellung eines neuen Trackingeintrags,<br>
  &nbsp;&nbsp;genutzt haben, wenn "NUR" dieser Eintrag angezeigt werden soll. Ein leeres default_portal stellt eine Auswahl,<br>
  &nbsp;&nbsp;aller Trackingeintrage zur Verf&uuml;gung und erm&ouml;glicht das Anzeigen eines beliebigen Eintrags.
        </p>
    </div>
    <?php endif; ?>
    
    <fieldset class="lwadminform">
        <div id="piwik_container" class="clearfix">
            <?php if($this->pageId): ?>
            <div class="piwik_container_graph_100pt_column">
                <h2>Seitenbesuche</h2>
                <img src="<?php echo $this->page_visits; ?>">
            </div>

            <div class="piwik_container_graph_50pt_column">
                <h2>User Browser</h2>
                <img src="<?php echo $this->browser; ?>">
            </div>

            <div class="piwik_container_graph_50pt_column">
                <h2>Aufrufszeiten</h2>
                <img src="<?php echo $this->servertime_visits; ?>">
            </div>

            <div class="piwik_container_graph_100pt_column">
                <h2>Verweisart</h2>
                <img src="<?php echo $this->refers; ?>">
            </div>

            <div class="piwik_container_graph_50pt_column">
                <div id="container_extend_min_height">
                    <h2>Die 10 am h&auml;ufigsten genutzten Seiten</h2>
                    <table>
                        <thead>
                        <th>Seitenname</th>
                        <th>Seitenansichten</th>
                        <th>Seitenbesuchsdauer</th>
                        </thead>
                        <tbody>
                            <?php $i = 0; foreach($this->mostUsedPages as $page_info): ?>
                            <?php if($i <= 9): ?>
                            <tr>
                                <td class="value_name"><?php echo $page_info["label"] ?></td>
                                <td class="value"><?php echo $page_info["nb_visits"] ?></td>
                                <td class="value"><?php echo $page_info["time_visit_sum_length_pretty"] ?></td>
                            </tr>
                            <?php $i++; endif; endforeach; ?>
                        </tbody>
                    </table>
                    <hr>
                    <h2 style="margin-top:10px;">Suchbegriffe<span id="close_all_infos">[close info]</span><br><span>(f&uuml;r Details Begriff anklicken)</span></h2>
                    <?php if($this->searchWords): ?>
                    <ol>
                        <?php $k = 1; foreach ($this->searchWords as $searchword): ?>
                        <?php if($k <= 10): ?>
                        <li>
                            <div id="show_se_info_<?php echo $k; ?>"><?php echo utf8_decode($searchword["label"]); ?> <span>(<?php echo $searchword["nb_visits"] ?>)</span></div>
                            <span id="se_container_<?php echo $k; ?>" >
                                <?php if(count($searchword["searchengine"]) >= 1): ?>
                                    <?php foreach($searchword["searchengine"] as $searchengine): ?>
                                        <img src="<?php echo $this->piwikBase.$searchengine["logo"]; ?>" > <span style="font-size: 11px;"><?php echo utf8_decode($searchengine["label"]) ?></span>  (<?php echo utf8_decode($searchengine["use_in_percent"]) ?>%) <br>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </span>
                        </li>
                        <?php $k++; endif; endforeach; ?>
                    </ol>
                    <?php endif; ?>
                </div>
            </div>


            <div class="piwik_container_graph_50pt_column">
                <h2>User L&auml;nder</h2>
                <img src="<?php echo $this->countries ?>">
            </div>

            <div class="piwik_container_graph_50pt_column">
                <h2 style="margin-top:10px;">Tagesinformationen <span>(<?php echo $this->pagename ?>)</span></h2>
                <table>
                    <tbody>
                        <tr>
                            <td class="pad_r">Anzahl eindeutiger Besucher :</td>
                            <td class="value"><?php echo $this->uniq_visitors ?></td>
                        </tr>
                        <tr>
                            <td class="pad_r">Anzahl der Seitenbesuche :</td>
                            <td class="value"><?php echo $this->visits ?></td>
                        </tr>
                        <tr>
                            <td class="pad_r">Durchschn. Aktionen pro Besuch :</td>
                            <td class="value"><?php echo $this->actions ?></td>
                        </tr>
                        <tr>
                            <td class="pad_r">Durchschn. Besuchsdauer (sek) :</td>
                            <td class="value"><?php echo $this->visit_time ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <?php else: ?>
                <div class="piwik_container_graph_100pt_column">
                    <h2>Bitte w&auml;hlen Sie eine Seite aus, f&uuml; die Sie die Statistiken einsehen wollen.</h2>
                </div>
            <?php endif; ?>
        </div>
    </fieldset>
</div>	